name: tag-push-image

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker-image:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          
      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: echo version
        run: echo ${{ steps.get_version.outputs.VERSION }}
      
      - name: print package.json
        run: cat ./home-web/package.json

      - name:  'Automated Version Bump'
        id: bump_version
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          PACKAGEJSON_DIR:  'home-web'
        with:
          tag-prefix:  'v'
          target-branch: 'main'

      # - name: Update version in package.json
      #   # You may pin to the exact commit or the version.
      #   # uses: maks-stupak/gh-action-bump-version@68745b36f06428d175b5aec775a41540ac1788aa
      #   uses: maks-stupak/gh-action-bump-version@v7.1.5
      #   with:
      #     # Prefix that is used for the git tag
      #     tag-prefix: "v"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      #     # Custom dir to the package
      #     PACKAGEJSON_DIR: "home-web"

      - name: print package.json again
        run: cat ./home-web/package.json

      # - name: use node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.15.4

      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      
      # - name: npm install packages
      #   run: cd ./home-web && npm install

      # - name: build project
      #   run: cd ./home-web && npm run build:ci

      - name: set up docker
        uses: docker/setup-buildx-action@v1

      - name: echo docker version
        run: docker version

      - name: build docker image with specific version tag
        run: cd ./home-web && docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.bump_version.outputs.newTag }} .

      - name: build docker image with latest tag
        run: cd ./home-web && docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest .

      - name: docker login
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: push image to registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.bump_version.outputs.newTag }}

      - name: push latest image to registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest